title: "Mechanical Ventilation"
description: "Useful Material for Difficult Situations"
baseurl: ""
url: "" 
theme: minima

include:
  - _css  # Explicitly include your CSS folder

plugins:
  - jekyll-feed
  - jekyll-data
  - jekyll-sitemap
  
data_dir: _data

audio:
  enabled: true
  files:
    mp3: "/music/ambient-study.mp3"
    ogg: "/music/ambient-study.ogg"
